### ISSUE TITLE
Can't open help files, opening the help patches crashes pd (Windows 64bit)

### ISSUE THREAD

**Issue by alex-esc** [porres/pd-cyclone#549] opened 2021-02-24 06:56 UTC
I am new to pd so at first I thought this was an issue on my end. I installed cyclone by following the readme. i tried from the find externals and by extracting the Files to `/externals`. But when I right click on an object (like scope~) and select 'help' I get this error message:
 
```
cyclone: can't open
(Tcl) INVALID COMMAND NAME: invalid command name ".x2610960.c"
    while executing
".x2610960.c delete all266ca70"
    ("uplevel" body line 766)
    invoked from within
"uplevel #0 $docmds"

```
I am able to use the object, but I cant open the help files. When I go to `...Documents\Pd\externals\cyclone` and click on a help file (for example `accum-help.pd`) pd freezes and crashes after a few minutes. Other externals (I tested with ELSE) work, including their help files.

I also tried re installing pd and I am still unable to open the help files. I am using pd version 0.51.4 on windows 10 64bit.

**Comment by Owibo** [comment] 2021-12-19 19:57
I'm having the same issue on Windows 10 and Ubuntu. The Help files do work on MacOS though

**Comment by porres** [comment] 2021-12-19 20:56
can you guys test [else/svfilter~]?

**Comment by porres** [comment] 2021-12-19 20:59
duplicate of https://github.com/porres/pd-cyclone/issues/579

**Comment by porres** [comment] 2021-12-19 21:08
this seems to be a problem with the [comment] object, can you and @jotschhh create this object?

and what about else/note, can you test to see if you can open its help file and use the object?

**Comment by porres** [comment] 2021-12-19 21:39
I need to know if EVERY help file shows this behaviour. Close and open PD with a few of these objects' help files just to test.

**Comment by porres** [comment] 2021-12-19 21:52
can any of you compile and see if  517acaf fixes this?

**Comment by porres** [comment] 2021-12-19 22:20
I cant reproduce any of these issues on a windows machine I have

Windows 10 Home 
21H1

**Comment by Owibo** [comment] 2021-12-20 18:20
> this seems to be a problem with the [comment] object, can you and @jotschhh create this object?
> 
> and what about else/note, can you test to see if you can open its help file and use the object?
(Windows)
I can create and edit the comment object without any problems
Went through every help file, closed Pd between files and every help file results in the same kind of error 
IIRC the help files used to work last year. It's not a huge problem, because the objects do work and the Max help files are available online

**Comment by porres** [comment] 2021-12-20 19:08
our help files are better :)

**Comment by emviveros** [comment] 2021-12-28 13:08
I tested it in Windows 10 PRO, Pd 0.51-4, Cyclone  0.6-0 without issues.

The only problem I have here was with automatic Cyclone initialization described in Readme. If I put in Startup Cyclone unless cyclone terminal returns to me:
![image](https://user-images.githubusercontent.com/3089536/147569214-b3f1fbfd-18b4-40ca-b2db-81b016026b17.png)

Initializing Cyclone in startup usin lowercase characters solve this.

I´m seeing this issue is from february. Maybe upgrading cyclone for the most recent version can solve it. (?)

**Comment by porres** [comment] 2022-04-17 08:06
@emviveros , it needs to be lower case

**Comment by porres** [comment] 2022-04-17 08:14
anwyam, I'm releasing an update soon, so we'll have binaries to test if this was really fixed! Heads up for @alex-esc , @OwenSSH and @ jotschhh

**Comment by porres** [comment] 2022-04-17 08:27
since I can't reproduce this error, it's hard for me to knw if I fixed it... so I really really need the collaboration of you people ( @alex-esc , @OwenSSH and @jotschhh ) to give me more details on what's going on and also test things

**Comment by Lucarda** [comment] 2022-04-19 03:21
@porres I think all this issue is about wrong paths. Since objects in help patches are instantiated with the perpended `cyclone/` Pd needs 2 paths: cyclone and its parent.

It should work Ok for normal setups like `$$$/Pd/externals/cyclone` mainly because `$$$/Pd/externals/` was an already added path but if you just add a path like `$$$/somewhere-in-my-hardrive/cyclone` help patches break (at least on Win and Linux).

**Comment by porres** [comment] 2022-04-19 03:30
I don't that's the problem, and we also have the 'tcl' error

**Comment by porres** [comment] 2022-04-23 18:38
without feedback, and with other people not being able to reproduce and help me, I see no other way than closing this - please reopen if you can help with the report

**Closed by porres** 2022-04-23 18:38 UTC
