### ISSUE TITLE
[pv x] and [send x] generates error

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-cyclone#163] opened 2016-11-30 12:18 UTC
The [value] object has this nice feature where it quietly communicates with [send]. So if you send a number to [send x] it will be stored by [value x] and can be retrieved with a bang as usual. I tested [pv] to see if it would do the same. It doesn't, and in fact it generates an error message. I don't know whether the link with [send] is desired behavior for [pv] (I would hope so). But either way, the error message is undesirable.

Note that I'm basing this off of the old version of Cyclone, so if you've changed [pv] then it may not be the case any more.

**Comment by porres** [comment] 2016-11-30 12:42
thanks, i'll look into that, i dont think it's a desired behaviour, anyway, we'll work in the error one way or another

**Comment by LGoodacre** [comment] 2016-11-30 12:57
I'll make the case that it is desired behavior (desired by me at least). Neither [value] and [pv] are strictly necessary objects in PD, but they are useful because they reduce the number of [receive]'s and [float]'s you need. The cross-communication with [send] further streamlines this, allowing for more efficient and elegant patches.

**Comment by LGoodacre** [comment] 2016-11-30 13:19
Can confirm that this error is still generated in the new 0.3pre-alpha-milestone5 release.

**Comment by porres** [comment] 2017-02-08 19:11
I've checked and confirmed the error, and I also checked that you can't have same named [send]/[pv] objects in Max

though we may consider this as an extra 'feature'

**Comment by porres** [comment] 2017-02-08 19:14
in Max it doesn't really let you create a send object if there's a pv object with the same name and vice versa! And it gives you an error like "x: already exists"or "pv: x: already exists"

**Comment by porres** [comment] 2017-02-08 19:15
in max you also have send and value but you don't ave both of them working like that, it does let you create send/v with the same name, though the values aren't shared

**Comment by porres** [comment] 2017-02-08 19:17
pv also wont be created if there's a v object with the same name in max, but in Pd it can coexist and won't print any error like with [send]

**Comment by porres** [comment] 2017-02-08 19:18
also maybe related, unlinke Pd, value objects do not communicate with expr in Max...

**Comment by porres** [comment] 2017-02-08 19:21
**we should really report that this value/send behaviour must be documented in Pd!!!**

**Comment by porres** [comment] 2017-02-08 19:26
but anyway, now that I think of it, doesn't really make sense to have [send] and [pv] because [pv] has this local behaviour by default, whereas send is global by nature - if you think about it, makes total sense that they can't talk to each other.

so, what we have to do now is think about how to deal with this error, if maybe prevent the object from creating, but we could do that to [pv] and not to [send] in pd, so it'd be inconsistent.

anyway, I guess we could keep it instantiating like that and maybe change the error to better explicitly say that there is a conflict with a send object, and also better document this whole thing in cyclone.

**Comment by porres** [comment] 2017-02-08 19:33
here's a test patch 
[test.pd.zip](https://github.com/porres/pd-cyclone/files/761766/test.pd.zip)

**Comment by porres** [comment] 2017-02-09 02:20
I Can't find in the code where the error is, seems the object was designed from pd's [value] and it used to generate such error before (in extended 0.42-5 for instance). So this feature between [send] and [v] is new!

**Comment by porres** [comment] 2017-02-09 02:35
anyway, I updated the documentation, but I'm still keeping this open because I'd like to check on what we could do about improving the error message

**Comment by porres** [comment] 2017-02-21 21:45
we should also allow it to instantiate without arguments!

**Comment by porres** [comment] 2017-03-04 02:58
change the error to better explicitly say that there is a conflict with a same named send object, and also better document this whole thing in cyclone.

**Comment by porres** [comment] 2017-03-04 03:05
It doesn't really make sense to have [send] and [pv] because [pv] has this local behaviour by default, whereas send is global by nature - if you think about it, makes total sense that they can't talk to each other.

so, what we have to do now is think about how to deal with this error. We could keep it instantiating like that and maybe change the error to better explicitly say that there is a conflict with a send object, and also better document this whole thing in cyclone.

we should also allow it to instantiate without arguments! Maybe give a warning when trying to send/retrieve data that it has no address, but let it create! And we totally need to get rid of "loud" errors, such as "error (miXed): missing or bad arguments in "pv""

**Comment by derekxkwan** [comment] 2017-04-21 00:46
hmm, looking at x_connective.c which defines the [send] class, i don't think it's possible to find out if there's a [send bob] for example, since bob isn't globally bound (unlike [value], which binds globally using pd_bind a vcommon_class to the given symbol). there's no pd_bind call for send.

**Comment by porres** [comment] 2017-04-21 16:38
don't get what you say, haha - but I see now that [pv] creates without arguments, awesome. I think this is important because you can then call the help file! In Max the object doesn't create, but you can open the help file anyway, in pd there's no way to do that - so it's a nice idea to make the object create anyhow, even if it can't be functional... (so we could print warnings and stuff).

Remembering that in Max it also doesn't create the [pv] object if there's a [send] or a [value] object with the same name, and vice versa. Since we can't change pd so it won't create [send] and [value] with the same name - there goes the max behaviour and opens the door for being minutely incompatible and adapted to the Pd world.

I see now that [pv] instantiates without arguments, but it is functional without them, not like I first thought, but maybe just fine (whatever). So it's loading an internal default symbol - what does [s]/[r]/[v] use for default address by the way?

Well, it being functional without args wouldn't be max behaviour, but could be an exception, like we have to make one way or another. And we can nicely document it.

The other idea would be to not make it functional and just print warnings, that it needed an argument to function, and that it can't work if there's a [send] or a [value] object with the same name. That's be trying to come closest to max compatibility.

But I actually like what we have now... it can create in any of such situations and it works, independently of [value] objects with the same name...

The only really annoying thing is that it has this error when you have a send object with the same name. Maybe we could simply get rid of that error and say and make it so that [pv] is completely independent from [value] and [send]/[receive] objects, as it is basically trying to be. That'd also be easy to document. Something like "unlike max, you can create [pv] objects with same name as [v]/[s] and they won't get in conflict" - done!

So, how to get rid of that annoying error when [send] with the same name as [pv] gets messages?

cheers

**Comment by derekxkwan** [comment] 2017-04-21 22:57
**pd_bind stuff**

well, the pd_bind function that I talked about is a way for something to be globally visible in pd by binding pd objects to symbols. value does it to bind float values (well, a pd object wrapped around a float value) to symbols. it's what i stole to make that clipboard for one of the cyclone objects (maybe funbuff?). it's how [receive] gets floats from corresponding sends, it binds itself (the current [receive] object) to the given symbol argument. somewhere, pd classes (like any object like [pv], [osc~], [array]) get bound to symbols too, but i haven't found exactly where yet. this gets done so when you type in the name of an object into a new object box, voila, you get the object.

[send] doesn't use pd_bind at all so (at least to my current thinking), you can't ask what it's bound to. when [send] gets something within its inlet, it figures out what type the stuff coming in is and calls pd_bang, or pd_float, or pd_symbol or whatever type it gets.

pd_float, defined in m_pd.c, just calls the float method associated with the bound symbol. 

long story short, pv used an internal pvlist class (but with no bound symbol so that's why you got ": no method for 'whatever'") as an equiv to value's vcommon ("value's global clipboard"), and i added dummy methods so that should be fixed. 

**default symbol for value**

value just uses &s_ (or whatever happens when you pass nothing as a symbol, i think that one) as a default symbol so that's why you have [s] with no args and [v] with no args, they work.

the current [pv] scans for &s_ and doesn't allow it (somewhere in its pvlist stuff) and i didn't want to mess with that for now, so using "_cyclone-pv-default" was a quicker fix. there's a good chance no sane person (well, except maybe me) would use that particular symbol as an argument and variables preceded by _ are typically hidden (it's a generally accepted practice (in python you see __VARIABLE__ name with VARIABLE replaced with whatever you want).

**Closed** 2017-04-21 23:14 UTC
