### ISSUE TITLE
Problem using cyclone with Windows

### ISSUE THREAD

**Issue by jotschhh** [porres/pd-cyclone#579] opened 2021-12-04 22:57 UTC
Hello, 
Iam fairly new to Pd, and just installed the cyclone addon and tried using the svf~ filter. 
When i try to open the Helptab for this function and sometimes even when i just type in [cyclone/svf~] i get the following error message: 
(Even after only having this object in the patch)
![Error](https://user-images.githubusercontent.com/95550663/144726951-e6426471-7a1a-47e3-b2bf-f3003d238b2e.png)

I tried both the 2021-08-05 and the 2020-11-25 Cyclone Version. 
Iam on a windows 10 Laptop, using the 0.51.3 Pd Version(64 Bit).

Maybe someone has the idea what is causing this problem and how to fix it?
Best wishes
Johannes

**Comment by jotschhh** [comment] 2021-12-04 23:09
Just tried the svf~ with the newest 0.51.4 Pd Vestion, and I get the same error.

**Comment by porres** [comment] 2021-12-19 21:01
duplicate of https://github.com/porres/pd-cyclone/issues/549

**Comment by porres** [comment] 2022-04-17 08:17
hey

**Comment by porres** [comment] 2022-04-17 08:19
hey @jotschhh , it's impossible that only creating svf~ can give this error, it does not have any tcl/tk code in it, so I think this may be related to the help file and I might have already fixed it... can you confirm that if you just initialize pd and create this object that it loads fine?

**Comment by porres** [comment] 2022-04-23 18:40
just like https://github.com/porres/pd-cyclone/issues/549 I will have to close this, you can also reopen this like i mentioned in the other issue - https://github.com/porres/pd-cyclone/issues/549

**Closed by porres** 2022-04-23 18:40 UTC
