### ISSUE TITLE
vectral~ noisy

### ISSUE THREAD

**Issue by wkc1986** [porres/pd-cyclone#355] opened 2017-11-25 02:12 UTC
Hi, I'm using `vectral~` to take a running average of fft amplitudes.
The resynthesis sounds fine when the patch first starts up, but as soon as I change the slide up/down time of `vectral~` from 0, the output becomes glitchy/distorted, almost like a downsampling effect, and stays that way even if I return the up/down time to 0. I'm on macOS Sierra and Pd vanilla 0.48.

MWE attached (just rename .txt to .pd).

[vectral-bug.txt](https://github.com/porres/pd-cyclone/files/1502749/vectral-bug.txt)

**Comment by porres** [comment] 2017-11-25 02:54
hi, thanks, vectral~ is known to be buggy and is one of the few we haven't fixed yet in the cyclone 0.3 release.

**Comment by wkc1986** [comment] 2017-11-25 02:59
Thanks for the update, Alexandre.

**Comment by porres** [comment] 2017-12-11 18:05
see also: https://github.com/porres/pd-cyclone/issues/250

**Comment by porres** [comment] 2018-01-12 23:54
I'm just putting another remark here that [vectral~] also needs a proper rampsmooth method, for now it's just a copy of slide :/

**Comment by porres** [comment] 2020-09-10 17:38
I'm closing this as I cannot reproduce it. I'm on macOS Mojave, using Pd 0.51-2 and cyclone 0.5-3.

I think it makes sense if you change the ramp values and the sound gets distorted, the problem would be if you went back to 0 and it kept the same, but going back to 0 for me restores the original signal...

**Closed by porres** 2020-09-10 17:38 UTC
Labels: bug
